In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("training.csv")
X = df.iloc[:, 2:].values
y = df.iloc[:, 0].values
print(X)

[[3861.66 3860.75 3861.38]
 [3861.38 3860.16 3861.25]
 [3861.38 3858.47 3858.53]
 ...
 [3795.09 3794.47 3794.91]
 [3795.13 3793.38 3794.34]
 [3794.66 3794.06 3794.47]]


In [3]:
d=0
for i in range(len(y)):
  if y[i]==1:
    d+=1
c=len(y)-d
print(d,c)

5039 4961


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 4975)

In [5]:
from sklearn.naive_bayes import ComplementNB 
classifier = ComplementNB()
classifier.fit(X_train, y_train)

ComplementNB()

In [6]:
import pickle
filename = 'finalized_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [7]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 0]
 ...
 [1 0]
 [0 0]
 [1 1]]


In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[266 242]
 [184 308]]


0.574

In [9]:
test_df=pd.read_csv("test_data.csv")
X_test = test_df.iloc[:, [1,2,3]].values
y_test = test_df.iloc[:, 4].values

In [10]:
d=0
for i in range(len(y_test)):
  if y_test[i]==1:
    d+=1
c=len(y_test)-d
print(d,c)

487 513


In [11]:
from sklearn.naive_bayes import ComplementNB 
classifier = ComplementNB()
classifier.fit(X, y)

ComplementNB()

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
df1 = pd.DataFrame()
df1['y_pred'] = y_pred
df1.head()


y_pred
0       0
1       1
2       0
3       1
4       1

In [14]:
df1.to_csv('prediction.csv',index=False)